/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.inventory.UI;

import java.awt.CardLayout;

/**
 *
 * @author akshitha
 */
public class ProductQuality extends javax.swing.JFrame {

    /**
     * Creates new form ProductQuality
     */
    CardLayout layout;
    String emp_id;
    public ProductQuality() {
        initComponents();
        layout = new CardLayout();
        displayPanel.setLayout(layout);
        displayPanel.add("ProductQuality", new QualityCheck());
//        displayPanel.add("Analyst", new Analyst());
    }
    public ProductQuality(String id){
        initComponents();
        emp_id = id;
        layout = new CardLayout();
        displayPanel.setLayout(layout);
        displayPanel.add("ProductQuality", new DeliverySignupPanel());
//        displayPanel.add("Analyst", new Analyst());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayPanel = new javax.swing.JPanel();
        navPanel3 = new javax.swing.JPanel();
        QualityCheck = new javax.swing.JButton();
        Analyst = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        displayPanel.setLayout(new java.awt.CardLayout());

        navPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        QualityCheck.setText("Quality Check");
        QualityCheck.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        QualityCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QualityCheckActionPerformed(evt);
            }
        });

        Analyst.setText("Analyst");
        Analyst.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Analyst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnalystActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navPanel3Layout = new javax.swing.GroupLayout(navPanel3);
        navPanel3.setLayout(navPanel3Layout);
        navPanel3Layout.setHorizontalGroup(
            navPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Analyst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(QualityCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        navPanel3Layout.setVerticalGroup(
            navPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navPanel3Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(QualityCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(Analyst, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(224, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 898, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(navPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(displayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(displayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(navPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void QualityCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QualityCheckActionPerformed
        addQualityCheck();
    }//GEN-LAST:event_QualityCheckActionPerformed

    private void AnalystActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnalystActionPerformed
        addAnalystPage();
    }//GEN-LAST:event_AnalystActionPerformed
    public void addQualityCheck(){
        layout.show(displayPanel, "ProductQuality");
    }
    public void addAnalystPage(){
        layout.show(displayPanel, "Analyst");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductQuality.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductQuality.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductQuality.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductQuality.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductQuality().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Analyst;
    private javax.swing.JButton DeliverySignup;
    private javax.swing.JButton DeliverySignup1;
    private javax.swing.JButton DeliverySignup2;
    private javax.swing.JButton QualityCheck;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JPanel navPanel;
    private javax.swing.JPanel navPanel1;
    private javax.swing.JPanel navPanel2;
    private javax.swing.JPanel navPanel3;
    // End of variables declaration//GEN-END:variables
}
